# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/junquan88/mysqltest C:\GithubLocalRepo'
- task: CmdLine@2
  inputs:
    script: 'dbforgemysql.com /execute /connection:"User Id=%jqtan%;password=%asdf1234%;Host=%localhost%" /inputfile "C- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'SqlTaskFile'
    SqlFile: 'C:\GithubLocalRepo\*.sql'
    ServerName: 'localhost'
    DatabaseName: 'mysqlbuild'
    SqlUsername: 'jqtan'
    SqlPassword: 'asdf1234'
    
